avoid helpbot crash if misconfigured
without this patch, if the helpbot channel would be set to None, it
would fail with:

    AttributeError: 'NoneType' object has no attribute 'lower' (file /usr/lib/python2.7/dist-packages/willie/tools.py, line 362, in _lower)

the modules in -extras should be enabled by default so this makes
"None" a valid value that makes the module be ignored. we also default
to None so that, by default, the helpbot module doesn't do anything